### PR TITLE
Work-In-Progress component added

### LINKED ISSUE #18: Create a WorkInProgress Component
@Dtech-Dbug  
### Issue Title: 
Create a WorkInProgress Component

### Description: 
**Objective:**  
Develop a `WorkInProgress` React component to inform users that a page is under construction.

### Necessity of the WorkInProgress Component

The `WorkInProgress` component is essential for enhancing user experience by providing clear feedback that a page is currently under construction. It helps manage user expectations, reducing frustration while they wait for content to be completed. This component serves as a visual indicator that development is ongoing, encouraging users to return later for a fully functional page.
temp77777

### PR DESCRIPTION
**Pull request by kshitijakarsh**
fixes #18 

I made a work-in-progress component and then replaced the collections route from "trending" as well as "explore" button to "work-in-progress" route. Also made changes to the logo, routed it to the home page.

Screenshot 2024-10-06 at 9 35 50 PM

### CODE REVIEW

**Review by Dtech-Dbug — COMMENTED** [review]
@kshitijakarsh can you follow the same structure/convention, we are following a specific case to name folders and files, lets maintain the consistency, please

**Comment by kshitijakarsh** [comment]
hey, can you please elaborate on that, what specific changes i need to make?

**Comment by Dtech-Dbug** [comment]
@kshitijakarsh  if you would observe the naming convetion / the case convention it generally considred best to follow the same conceptual integrity throughout the codebase... inlude naming of files folderc etc. 
If we are using camelCase for file names, lets makes ure to maintain that everywhere...
all your file names and folders are named in all lower case. we dont have all lowecase file names., 


and also sort the files where they belong -  under proper folder - if its a component place it under `Components` folder, if its a page in itself put it in `Pages` dir. 
in your case - `WIP` component should ideally be under`Components` and we will re-use this everywhere. 

Is that clear?

**Comment by kshitijakarsh** [comment]
hey made the changes, do go through it and tell me if there's anymore corrections to be made.

**Pull request merged**
