### PR TITLE
 🚀Added Backend with Scrapers and Frontend Search Feature

### PR DESCRIPTION
**Pull request by piyushpatelcodes**
### 🎉 Hacktoberfest 2024 Contribution 🎉
# Pull Request for Backend with Scrapers and Frontend Features.

## Overview

This pull request introduces significant enhancements to the project by adding a backend with proxy servers to overcome CORS issues when scraping data from meme template sites. The changes also include a dynamic meme search feature on the frontend, allowing for a more interactive and user-friendly experience. I also Added Lazy loading such that scraper backend does not have to load 1000 files at once instead it works in background and use pre-rendering for fast reloads

### Backend Improvements
- **Proxy Server Setup**: Implemented a proxy server to prevent CORS policy issues when scraping data directly from the frontend.
- **CORS Policy**: Configured the backend to handle CORS requests effectively.
- **Dynamic Data Fetching**: Added a scraper that dynamically fetches data from the meme template site, eliminating the need for hard-coded memes in the codebase.

### Frontend Enhancements
- **Search Bar with Suggestions**: Introduced a search bar that offers suggestions as users type, providing an intuitive interface for searching memes.
- **Dynamic Meme Names**: Each meme now displays its name on hover, enhancing user interaction.
- **Unique UI Design**: Focused on creating a visually appealing UI for the search bar, making it aesthetically pleasing and user-friendly.
- **Efficient Search Functionality**: The search feature is optimized for speed and efficiency, ensuring quick results.
- **Lazy Loading**: Implemented lazy loading for memes, reducing server load by only loading memes as the user scrolls to the end of the list.

## Usage Instructions
- **Backend Hosting**: The backend is not hosted by default. It can be run locally on your machine.
- **Localhost**: Ensure your backend is running on localhost for the frontend to connect successfully.
- **Global Hosting**: For global access, you can host the backend on platforms like Vercel or Railway for free. 

### Steps for Global Hosting
- [ ] Deploy the backend on Vercel or Railway.
- [ ] Replace the backend URL in the `config.js` file located in the root directory of the project.

### Original Code review
https://github.com/user-attachments/assets/147384d3-c234-4b0b-9f06-692802d9f472

### Updated Code review

https://github.com/user-attachments/assets/e299b1dc-e9d5-4464-b7a0-5d2e2d927bec

## Author
- **Piyush Patel**  
  GitHub: [GitHub Profile - piyushpatelcodes](https://github.com/piyushpatelcodes) 
  Email: piyushpatelcodes@gmail.com  

## Conclusion
These enhancements improve the overall functionality and usability of the application. The backend ensures reliable data fetching without being limited to hard-coded memes, while the frontend provides an engaging user experience with an efficient search feature.

---

Thank you for considering my pull request!

### CODE REVIEW

**Comment by Dtech-Dbug** [comment]
@piyushpatelcodes wonderful work on the search feature!! 

but the styles arent latest, can you make sure to run `git rebase master`  to make sure your feature branch has the latest master/main changes - bc i merged a style change PR.

**Comment by piyushpatelcodes** [comment]
Ok I will do that.

**Comment by piyushpatelcodes** [comment]
@Dtech-Dbug  Hey!. I just merged all the conflicts and rebased the code. Now you can mere this PR. also if you are willing to merge my pull request then please look for backend.

- As soon as you accept the PR. you must host the backend on VERCEL or Railway website. 
- After hosting the backend please replace the **_"Sample Backend Url"_** with your **_"Hosted Backend URL"_** in ._**/config.js file**_

### `Also Can you Please Mark/Label this Pull Request as Hacktoberfest Label and with other Related Tags`

**Comment by piyushpatelcodes** [comment]
# ✨Hacktoberfest 2024 Contributions
# New Update - Home Page introduced
@Dtech-Dbug  Hey! I just introduced a New Home Page / Landing Page. you can Merge This PR if you like it. I also Hosted The backend on render.com as discussed in previous comments.

## New Updated HomePage


https://github.com/user-attachments/assets/f7441177-45d7-4601-ba86-6b08a26ba0e6

if you like my PR please merge it. if you have suggestion or want to change something in this update, i will do it and update you in this PR itself and then you can merge it.
> [!Tip]
>  Can You Please Mark/Label this Pull Request as Hacktoberfest Label and with other Related Tags

**Comment by piyushpatelcodes** [comment]
@Dtech-Dbug As requested, the backend has been refactored to integrate with the frontend database, resulting in a comprehensive collection of meme templates containing **10,000 meme templates** available for immediate use. 

### New Features
- **Removed Backend :** Now Backend has Been Removed and Now we have 10,000 Scraped Meme Templates along with their Category.
- **Search Debounce & Lazy Loading:** Implemented search debounce functionality to enhance the performance of meme searching, ensuring a smooth user experience.
- **Documentation of Meme Categories:** All categories of memes have been documented, along with their respective source links for easy reference.
- Also Added Contributers Section In The Readme.md File.

## Instructions for Scrapers
For those looking to scrape additional meme templates, please follow the instructions outlined in the `README.md` file. This will guide you through the process of using the scrapers effectively.

> [!TIP]
> Can You Please Mark/Label this Pull Request as Hacktoberfest Label and with other Related Tags

**Comment by Dtech-Dbug** [comment]
@Wasif0787 checkout this : `https://github.com/Dtech-Dbug/MemeTem/pull/7#issuecomment-2389537219` 

this landing page seems dope too - 
is there any cha ce you two can sync up and combine the splash screen and landing page together to HAVE JUST ONE SCREEN  to give user a overview of what we are, latest , trending memes etc... (BEFORE USER IS SHOWN THE FEED)

Could i request @Wasif0787  and @piyushpatelcodes  to collab together ESPECIALLY ON THIS ONE(the screen)!!!

**Comment by Wasif0787** [comment]
I think the nav bar should be removed from the splash screen, it not looking good

**Comment by Dtech-Dbug** [comment]
how do you suggest the flow of screens should be? @Wasif0787

**Comment by Wasif0787** [comment]
Let the splash screen appear for few secs then the homepage

**Comment by Dtech-Dbug** [comment]
@Wasif0787 alright - considering the splash screen only appears ONCE unless session is reset from dev tools. 
Also, i liked the theme of the landing page - is there any way you can use the same colors in the splash screen?

**Comment by Wasif0787** [comment]
Okay , I'll look for it , and I think no need to add daisy ui now

**Comment by Dtech-Dbug** [comment]
also, here is a creazy idea - 
how about this 

in the splash screen (besides what is already there) how about we add a shower or confetti of the laughing emohi 😆  or 😆  which is relevant to our 'MEME' culture... 

does it sound quirky?
can we do this? I would love to help as well, 

its very much like the package `react-confetti` but instead of confettis we will show emojis...

**Comment by Dtech-Dbug** [comment]
@Wasif0787 example of react confetti : `https://codepen.io/Gthibaud/pen/ENzXbp`

**Comment by Dtech-Dbug** [comment]
@Wasif0787  good news, i tried that medium blog out, it works!! we can add custom emojis... 
let's go ahead and use emoji confettis in home screen - can you work on it today? and raise a PR? 

- make the splash screen follow the saem color theme of the landing (0.1 effort)
- use emoji confetti (0.2) 

I think this shouldnt take a lot of efforts, but even then if you need any assist, pls feel free to buzz me.

**Comment by Dtech-Dbug** [comment]
https://github.com/user-attachments/assets/018b8535-2bc7-4df9-8c29-336ca17bc84a

@Wasif0787  @piyushpatelcodes  added the emoji confettis, in the splash screen FYI 

Please make sure you `PULL MY LATEST` on your feature branches respectively...

**Review by Dtech-Dbug — COMMENTED** [review]
what is this file doing? `scrapedImages.json` and how is it diff from the json files under `Data/memeTemplates` 
and where is it being used contents from `scrapedImages` being used?

**Comment by piyushpatelcodes** [comment]
@Dtech-Dbug  All Backend Files are now private to me.

> what is this file doing? `scrapedImages.json` and how is it diff from the json files under `Data/memeTemplates` and where is it being used?

When Scrapper extract the content it automatically loads all its data in a json file which is `scrapedImages.json` .  Now we can simply merge  this json with other scrapped data  json file and add content to it.

**Pull request merged**
