### PR TITLE
updated .Meme-template-container in App.css

### PR DESCRIPTION
**Pull request by Ramya-Clg**
I have updated the  .Meme-template-container in App.css so that the number of columns are dynamic to fit the width of the meme with minimum width of 200px and also changed the css for the image tags inside  .Meme-template-container so that the meme takes 100% width and the height is set automatically to adjust according to aspect ratio. The homepage looks much better than before 

## Previous Page:
image

## New Page:
image

### CODE REVIEW

**Comment by Dtech-Dbug** [comment]
@Ramya-Clg wonderful work! Really preciate it. 
Did you also check in mobile view? Could you pls maybe also add a preview in mobile view, to see if its the responsive and preserving the new styles.

**Comment by Ramya-Clg** [comment]
Yes sure here are some previews for the mobile view

image
Screenshot 2024-10-01 152158

**Comment by Dtech-Dbug** [comment]
@Ramya-Clg well done! 
in some pics can you make the image contain, bc in some pics the thumbnail isnt containing the image

**Comment by Ramya-Clg** [comment]
Ok I will try to see if I can do something about it.

**Comment by Ramya-Clg** [comment]
This is how it looks in 
mobile screen:
image
full window:
Screenshot 2024-10-01 221937

**Pull request merged**
